version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=host.docker.internal
            - DB_PORT=3306
            - DB_DATABASE=kafka_app
            - DB_USERNAME=root
            - DB_PASSWORD=1234
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8001:8001"
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        restart: unless-stopped
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_NUM_PARTITIONS: 1
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        networks:
            - laravel_network

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        restart: unless-stopped
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge
